// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqzptqerxytfmqcttrjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxenB0cWVyeHl0Zm1xY3R0cmpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDIzMzUsImV4cCI6MjA2OTgxODMzNX0.iJYTQFgXvIBqAO-EqM2-aLZq2KBMi-C2iAb7bV-kj1U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});